spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/picker-auth-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/changelog-master.yml'
